### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MiClobiMC** [Cantersoft/YTPMVE#1]
when I load the midi file it gives me an error

**Comment by Cantersoft** [comment]
Hey there! I didn't actually intend for anyone to find this yet, and thus there are no setup instructions! This software only works under very specific conditions so please wait for me to finish making a video tutorial explaining how it works. It will be uploaded on [my channel](https://www.youtube.com/c/Cantersoft) within around a week-- feel free to check back in that timeframe or subscribe.

**Comment by Cantersoft** [comment]
**Update**: Because I was unfortunately unable to fulfill my promise, I decided to add a README with instructions instead. Feel free to open another issue if there's another problem.
