### ISSUE TITLE
Vuelvo despues de tanto tiempo y siguen los problemas

### ISSUE THREAD

**Issue by MiClobiMC** [Cantersoft/YTPMVE#12]
He probado la nueva version del ytpmv y me sigue dando el mismo error he probado con la misma cancion mid quizas con otra me funcione pero no encuentro una que sea type 0 quizas sea el sony vegas he formateado mi pc ya 3 veces y sigue pasando lo mismo no se si habra otro editor de video o de forma independiente quizas me funcione

**Comment by solstice-r** [comment]
El archivo midi debe contener una sola pista, puedes crear un archivo así usando reaper, hice un video (en inglés) sobre cómo hacerlo aquí: 
https://youtu.be/-JxLqvnv6u0
Hazme saber si esto funciona, también puedo traducir el texto del video en español si eso ayuda.

----

The midi file needs to only contain a single track, you can create a file like that using reaper, I made a video (in english) on how to do so here: 
https://youtu.be/-JxLqvnv6u0

**Comment by MiClobiMC** [comment]
Acabo de probar y me da el mismo error que se bug la pista se repite por horas

**Comment by solstice-r** [comment]
mind sending over the midi file?

----
¿te importaría enviar el archivo midi?

**Comment by MiClobiMC** [comment]
Aqui esta
[River.Flows.in.You.zip](https://github.com/Cantersoft/YTPMVE/files/7429942/River.Flows.in.You.zip)

**Comment by solstice-r** [comment]
![image](https://user-images.githubusercontent.com/49078943/139413370-7628be49-2252-426f-b395-3312657f3673.png)

Looks like there's still overlapping notes in the midi file, are you sure you removed all of them?

----

Parece que todavía hay notas superpuestas en el archivo midi, ¿estás seguro de que las has eliminado todas?

<br>
<br>

![image](https://user-images.githubusercontent.com/49078943/139413942-2abef532-6832-479e-945b-cf79bd59f698.png)
Even though there are overlapping notes, the script seems to work correctly for me, what version of Vegas are you using?

----

Aunque hay notas superpuestas, el script parece funcionar correctamente para mí, ¿qué versión de Vegas estás utilizando?

**Comment by MiClobiMC** [comment]
La version 18 estoy usando pero no se por que me pasa esto solo a mi que ocurre ese bug

**Comment by solstice-r** [comment]
hm, could you send a screen recording of you using the script on the midi file?

----
hm, ¿podría enviar una grabación de pantalla de usted usando el script en el archivo midi?

**Comment by MiClobiMC** [comment]
Este es el error el mismo de hace un tiempo https://www.youtube.com/watch?v=yM5-z4EI7mQ

**Comment by solstice-r** [comment]
you're using a very old version of ytpmve, get a new one from the [releases tab](https://github.com/Cantersoft/YTPMVE/releases)

----
estás usando una versión muy antigua de ytpmve, obtén una nueva desde la [pestaña de versiones](https://github.com/Cantersoft/YTPMVE/releases)

**Comment by MiClobiMC** [comment]
La del video es vieja pero ahora estoy usando la ultima version del ytpmv y me sigue dando el mismo error seria innecesario grabar de nuevo

**Comment by solstice-r** [comment]
never saw something like that, could it be because you're using subclips?

----
Nunca vi algo así, ¿podría ser porque estás usando subclips?

**Comment by MiClobiMC** [comment]
No lo se voy a probar con un video ya editado y luego volver a importarlo en el sony vegas

**Comment by MiClobiMC** [comment]
Acabo de probar con un video de 1 segundo sin subclip y me sigue pasando lo mismo

**Comment by Cantersoft** [comment]
El problema no es a causa de los subclips, creo que hay algo equivocado en YTPMVE todavía. 
@MiClobiMC Mira al otro mensaje que te envié. Vamos a ver si la nueva prueba arregle el problema finalmente.
