### ISSUE TITLE
Pitch shift?

### ISSUE THREAD

**Issue by fttongithub2** [Cantersoft/YTPMVE#15]
I know it may be useless to you but for people like me that or lazy or do not use music programs, It would be useful. Again, You can contribute so someone out there might add it in the future.

**Comment by Cantersoft** [comment]
You make a fair point. I'll probably do this eventually. I'd like to add more controls first, such as screen flipping.

**Comment by Cantersoft** [comment]
Almost a year later and I finally got around to this. Automatic pitch shift is implemented. 
Life's been busy and I've been lazy.

**Comment by fttongithub2** [comment]
ty!
