### ISSUE TITLE
Automatically generate visuals and effects from other videos?

### ISSUE THREAD

**Issue by Lilothestitch16** [Cantersoft/YTPMVE#16]
Hi. Would it be possible to add a feature where we can autogenerate visuals and effects from other YTPMV Videos? I have some samples.

YOUKAI ZONE: https://www.youtube.com/watch?v=arA11LpHo00

Shibamata: https://www.youtube.com/watch?v=FIw-HUP7XK0

WORLD ZONE: https://youtu.be/BEd2EFtg9BA

Smoooooch ZONE: https://www.youtube.com/watch?v=u_hsNTsVc2I

**Comment by Cantersoft** [comment]
For some of those effects what you'd need to do is generate the YTPMV normally and export from Vegas first, and then import the result into a stronger effects software such as HitFilm or After Effects. I tried really hard to get complicated stuff like that to work in Vegas before, but trust me, you won't get as good results and it's much harder. However, using layer motion tracking will get you part of the way there.

If you have a specific feature idea though and are aware of a way to integrate it in with the scripting API, let me know!
