### ISSUE TITLE
Multitrack MIDI not supported

### ISSUE THREAD

**Issue by MiClobiMC** [Cantersoft/YTPMVE#2]
This is what happens when I load the midi file
![errorytpmv](https://user-images.githubusercontent.com/60762569/121092422-86d64a80-c7b9-11eb-8580-546e3f151666.JPG)

**Comment by Cantersoft** [comment]
This is because there are multiple tracks in that MIDI file, as the error says. Remove all the tracks from the MIDI except for the one you want to use (probably the melody) and it will work.

Multitrack MIDI support will be added later.

**Comment by Cantersoft** [comment]
Multitrack MIDI support has now been added.
