### ISSUE TITLE
no work i think (VEGAS 14.0 CRACKED problem)

### ISSUE THREAD

**Issue by BillShakerYT** [Cantersoft/YTPMVE#20]
C:\Program Files\VEGAS\VEGAS Pro 14.0\Script Menu\YTPMVE.cs(204) : 'ScriptPortal.Vegas.AudioEvent' does not contain a definition for 'PitchSemis' and no extension method 'PitchSemis' accepting a first argument of type 'ScriptPortal.Vegas.AudioEvent' could be found (are you missing a using directive or an assembly reference?)

Any fixes?

**Comment by Cantersoft** [comment]
Hi, I just looked into this. I did not realize, but apparently pitch shifting through scripting was not possible in Vegas 14. I'll add some logic to the code to prevent this error, but the script will only generate the clips to the rhythm-- it won't pitch shift. 

Do you have a newer version of Vegas available? I can provide Vegas 17 if needed.

**Comment by Cantersoft** [comment]
Alright, I've released a patch for this issue, Just reinstall to get the video functionality. As I mentioned though, pitch shifting won't work.
