### ISSUE TITLE
Error generate ytpmv

### ISSUE THREAD

**Issue by MiClobiMC** [Cantersoft/YTPMVE#4]
When loading the MIDI file it appears as it is generating but at the end it does not generate it use this MIDI file https://www.mediafire.com/file/p4ilgn3e8z3tq8k/River_Flows_In_You.zip/file
![errorytpmvinvalid](https://user-images.githubusercontent.com/60762569/121267989-0b44ce00-c88b-11eb-9257-c297a1099423.JPG)

**Comment by Cantersoft** [comment]
I'm assuming you were unable to read the message because is not in your language. It's just telling you that some of the clips couldn't be placed properly. Most of them were. Just click "OK" (or "Aceptar" in your case) and everything will be generated properly.
